default: &default
  adapter: sqlite3
  pool: 5

development:
  <<: *default
  database: db/development.sqlite3
test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  database: uts_production
  pool: 5
  timeout: 5000